#!/usr/bin/env bash
#
# nginx-setup.sh — pasang reverse-proxy nginx + SSL (certbot) untuk KePin.
#
# Membuat config BARU di /etc/nginx/sites-available + symlink ke
# sites-enabled. Tidak mengubah/menghapus config nginx lain (default,
# ozora, dll). Aman dijalankan ulang (idempotent).
#
# Alur: tulis config HTTP → terbitkan sertifikat (certonly --webroot,
# certbot TIDAK memodifikasi config) → tulis config final ber-SSL →
# reload. Sertifikat direnew otomatis oleh certbot (timer systemd).
#
# Usage:
#   ./scripts/nginx-setup.sh <domain> <api-domain>
#   Contoh: ./scripts/nginx-setup.sh kepin.oryphem.com api.kepin.oryphem.com
#
# Env override: FRONTEND_PORT (default 3001), BACKEND_PORT (default 8001)
set -euo pipefail

DOMAIN="${1:?usage: nginx-setup.sh <domain> <api-domain>}"
API_DOMAIN="${2:?usage: nginx-setup.sh <domain> <api-domain>}"
FRONTEND_PORT="${FRONTEND_PORT:-3001}"
BACKEND_PORT="${BACKEND_PORT:-8001}"

CONF="/etc/nginx/sites-available/${DOMAIN}"
LINK="/etc/nginx/sites-enabled/${DOMAIN}"
CERT_DIR="/etc/letsencrypt/live/${DOMAIN}"
WEBROOT="/var/www/html"
CERT_FULLCHAIN="${CERT_DIR}/fullchain.pem"
CERT_PRIVKEY="${CERT_DIR}/privkey.pem"

echo "→ Setup nginx reverse-proxy:"
echo "    ${DOMAIN}     → http://127.0.0.1:${FRONTEND_PORT}  (frontend)"
echo "    ${API_DOMAIN} → http://127.0.0.1:${BACKEND_PORT}  (backend)"

# ── Cek DNS (warning saja, biar error certbot mudah dipahami) ────────────────
LOCAL_IPS="$(hostname -I 2>/dev/null || true)"
for H in "${DOMAIN}" "${API_DOMAIN}"; do
  IP="$(getent hosts "${H}" | awk '{print $1; exit}')"
  if [ -z "${IP}" ]; then
    echo "  ⚠ DNS ${H} tidak resolve — pastikan A record menunjuk ke server ini."
  elif ! echo "${LOCAL_IPS}" | grep -qw "${IP}"; then
    echo "  ⚠ ${H} → ${IP} (bukan IP server ini: ${LOCAL_IPS})"
  else
    echo "  ✓ ${H} → ${IP} (server ini)"
  fi
done

mkdir -p "${WEBROOT}"
mkdir -p /etc/nginx/sites-available

# ── 1) Config HTTP (untuk acme-challenge + redirect) ─────────────────────────
#    Ditulis ulang hanya jika belum ada SSL di config (proses awal).
if [ ! -e "${CONF}" ] || ! grep -q "ssl_certificate" "${CONF}" 2>/dev/null; then
  cat > "${CONF}" <<EOF
# KePin — generated by scripts/nginx-setup.sh (${DOMAIN})
server {
    listen 80;
    server_name ${DOMAIN};

    location ^~ /.well-known/acme-challenge/ {
        root ${WEBROOT};
        try_files \$uri =404;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 80;
    server_name ${API_DOMAIN};

    location ^~ /.well-known/acme-challenge/ {
        root ${WEBROOT};
        try_files \$uri =404;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}
EOF
  if [ ! -e "${LINK}" ]; then
    ln -s "${CONF}" "${LINK}"
    echo "→ Config ${LINK} diaktifkan (config lain tidak disentuh)."
  fi
  nginx -t
  systemctl reload nginx
  echo "→ nginx reload OK (HTTP aktif, siap acme-challenge)."
fi

# ── 2) Terbitkan sertifikat SSL (sekali; renew otomatis oleh certbot) ────────
if [ ! -d "${CERT_DIR}" ]; then
  echo "→ Terbitkan sertifikat SSL untuk ${DOMAIN} & ${API_DOMAIN} ..."
  certbot certonly --webroot -w "${WEBROOT}" \
    -d "${DOMAIN}" -d "${API_DOMAIN}" \
    --non-interactive --agree-tos
fi

# ── 3) Config final dengan SSL (deterministik, aman dijalankan ulang) ────────
cat > "${CONF}" <<EOF
# KePin — generated by scripts/nginx-setup.sh (${DOMAIN})
server {
    listen 443 ssl;
    server_name ${DOMAIN};

    ssl_certificate ${CERT_FULLCHAIN};
    ssl_certificate_key ${CERT_PRIVKEY};

    location / {
        proxy_pass http://127.0.0.1:${FRONTEND_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffer_size 16k;
        proxy_buffers 8 16k;
    }
}

server {
    listen 443 ssl;
    server_name ${API_DOMAIN};

    ssl_certificate ${CERT_FULLCHAIN};
    ssl_certificate_key ${CERT_PRIVKEY};

    location / {
        proxy_pass http://127.0.0.1:${BACKEND_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_buffer_size 16k;
        proxy_buffers 8 16k;
    }
}

server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 80;
    server_name ${API_DOMAIN};
    return 301 https://\$host\$request_uri;
}
EOF

nginx -t
systemctl reload nginx

echo ""
echo "✓ Selesai:"
echo "  https://${DOMAIN}"
echo "  https://${API_DOMAIN}/docs"